### ISSUE TITLE
Volume ownership

### ISSUE THREAD

**Issue by d5ve** [K4rian/docker-twserver#1]
Many thanks for twserver and docker-twserver.

Do you have any suggestions about mounting host directories into the container with docker-compose?

When I follow the `docker run` instructions from the README, either directly, or with docker-compose the container fails to start as the host machine directory seems to overwrite `/home/tw/twserver` so nothing starts.

My run command looks like:
`docker run -d --rm --name twserver -v /data/tiddlywiki:/home/tw -p 8080:8080 k4rian/twserver`

My docker-compose.yml file looks like:
```
version: "3.7"
services:
  twserver:
    image: "k4rian/twserver:latest"
    container_name: "twserver"
    volumes:
      - type: bind
        source: /data/tiddlywiki
        target: /home/tw
```

Then, if I change it to mount `/home/tw/www`, and `/home/tw/backup` individually, the service starts up, but there are file permission issues, and the server silently fails to update the index.html file upon tiddly save, and no backup files are created.

Any ideas would be gratefully received.

Cheers,

Dave Webb

**Comment by K4rian** [comment]
Hi,

Thanks for your interest in the project.

You should use `volume` over `bind` whenever possible to avoid any kind of unexpected behaviors on the file system. In your case the compose file should look like this (on a local machine):

```
version: "3.7"

services:
  tiddlywiki:
    image: k4rian/twserver:latest
    container_name: twserver
    network_mode: host
    volumes:
      - type: volume
        source: twserver_data
        target: /home/tw

volumes:
  twserver_data:
```
To retrieve the volume path you can use the following command:
```
$ docker inspect -f '{{  .Mounts }}' twserver
```

If you _really_ want to store your volume data in any custom location, you should take a look at the [**local-persist**](https://github.com/MatchbookLab/local-persist) plugin project page on GitHub.

Hope this helps!
